
[31;01mException occurred:[39;49;00m
  File "/home/luc/hgwork/atelier/atelier/sphinxconf/base.py", line 118, in get_blog_url
    if not atelier.BLOG_URL:
AttributeError: 'module' object has no attribute 'BLOG_URL'
[31;01mThe full traceback has been saved in /tmp/sphinx-err-kj3d41.log, if you want to report the issue to the developers.[39;49;00m
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
