=====================================
20140108 (Wednesday, 08 January 2014)
=====================================


AttributeError: AttrDict instance has no key 'CitiesByCountry'
--------------------------------------------------------------

The following snippet reproduces a wrong which occurred when a certain
kind of invalid url was being requested. Lino should return a 404
status in that case, not raise an :ref:`ise`.

>>> from __future__ import print_function
>>> import os
>>> os.environ['DJANGO_SETTINGS_MODULE'] = 'lino.projects.belref.settings.test'
>>> from django.test import Client
>>> from lino import dd
>>> dd.startup()
>>> client = Client()
>>> url = '/countries/CitiesByCountry'
>>> res = client.get(url)
>>> print(res.status_code)
404






